# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# a matrix list of variables used in the container build process
# it is used to define what ansible core images that define both ansible core and the python interpreter
# are going to be used in the container build process for the collection.
#
# python version are taken from ansible's support matrix - https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#support-life
# ansible-core-image version is taken from https://github.com/orgs/srl-labs/packages?repo_name=ansible-core
include:
  # 2.14
  - ansible-core-image: "2.14.17:pypy3.10"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.14.17:py3.11"
    runs-on: "ubuntu-22.04"
    addional-tags: "latest"

  # 2.15
  - ansible-core-image: "2.15.12:pypy3.10"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.15.12:py3.11"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.15.12:py3.12"
    runs-on: "ubuntu-22.04"
    addional-tags: "latest"

  # 2.16
  - ansible-core-image: "2.16.8:pypy3.10"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.16.8:py3.11"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.16.8:py3.12"
    runs-on: "ubuntu-22.04"
    addional-tags: "latest"

  # 2.17
  - ansible-core-image: "2.17.1:pypy3.10"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.17.1:py3.11"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.17.1:py3.12"
    runs-on: "ubuntu-22.04"
    addional-tags: "latest"
