# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# a matrix list of variables used in the container build process
#
# python version are taken from ansible's support matrix - https://docs.ansible.com/ansible/latest/reference_appendices/release_and_maintenance.html#support-life
# ansible-core-image version is taken from https://github.com/orgs/srl-labs/packages?repo_name=ansible-core
include:
  # 2.14.11
  - ansible-core-image: "2.14.11:pypy3.10"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.14.11:py3.11"
    runs-on: "ubuntu-22.04"
    addional-tags: "latest"

  # 2.15.5
  - ansible-core-image: "2.15.5:pypy3.10"
    runs-on: "ubuntu-22.04"

  - ansible-core-image: "2.15.5:py3.11"
    runs-on: "ubuntu-22.04"
    addional-tags: "latest"

  - ansible-core-image: "2.15.5:py3.12"
    runs-on: "ubuntu-22.04"
