# Copyright 2023 Nokia
# Licensed under the BSD 3-Clause License.
# SPDX-License-Identifier: BSD-3-Clause

# a matrix list of variables used in testing
# kind of a manual way of creating a testing matrix with a flexibility of selecting permuatations
# support matrix for ansible control node - https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html#node-requirement-summary

include:
  # Python 3.8
  - &latest-2_12
    python-version: "3.8"
    ansible-core-version: "2.12.10"
    runs-on: "ubuntu-22.04"

  - &latest-2_13
    python-version: "3.8"
    ansible-core-version: "2.13.13"
    runs-on: "ubuntu-22.04"

  # Python 3.9
  - <<: *latest-2_12
    python-version: "3.9"

  - <<: *latest-2_13
    python-version: "3.9"

  - &latest-2_14
    python-version: "3.9"
    ansible-core-version: "2.14.11"
    runs-on: "ubuntu-22.04"

  - &latest-2_15
    python-version: "3.9"
    ansible-core-version: "2.15.5"
    runs-on: "ubuntu-22.04"

  # Python 3.10
  - <<: *latest-2_12
    python-version: "3.10"

  - <<: *latest-2_13
    python-version: "3.10"

  - <<: *latest-2_14
    python-version: "3.10"

  # Python 3.11
  - <<: *latest-2_12
    python-version: "3.11"

  - <<: *latest-2_13
    python-version: "3.11"

  - <<: *latest-2_14
    python-version: "3.11"

  - <<: *latest-2_15
    python-version: "3.11"

  # Python 3.12
  - <<: *latest-2_12
    python-version: "3.12"

  - <<: *latest-2_13
    python-version: "3.12"

  - <<: *latest-2_14
    python-version: "3.12"

  - <<: *latest-2_15
    python-version: "3.12"
